In [1]:
def compute_gradient(x,y,w,b):
    """
    Computes the gradient for linear regression.
    
    Args:
        x (ndarray): Shape (m,n) Input to the model (features of students)
        y (ndarray): Shape (m,) Target (final grade G3 of students)
        w (ndarray): Shape(n,) Parameter of a model
        b (scalar): Parameter of a model
    Returns:
        dj_dw (ndarray): Shape (n,) The gradient of the cost function depending on parameter w
        dj_db (scalar): The gradient of the cost function depending on parameter b
    """
    
    m = x.shape[0]
    n = x.shape[1]
    
    dj_dw = np.zeros(n)
    dj_db = 0
    
    dj_dw_sum = np.zeros(n)
    dj_db_sum = 0
    
    for j in range(n):
        for i in range(m):
            func = np.dot(w, x[i]) + b
            dj_dw_i_j = (func - y[i])*x[i][j]
            dj_dw_sum[j] = dj_dw_sum[j] + dj_dw_i_j
        dj_dw[j] = dj_dw_sum[j]/m
        
    for i in range(m):
        func = np.dot(w, x[i]) + b
        dj_db = func - y[i]
        dj_db_sum = dj_db_sum + dj_db
    dj_db = dj_db/m
    
    
    return dj_dw, dj_db
    
    
            
            
    
    
    

In [27]:
import numpy as np
x = np.array([[1,2,3],
              [4,5,6]])
              
y = np.array([1,2])
w = np.array([0.1,0.2,0.3])
b = 1

In [29]:
a, b = compute_gradient(x,y,w,b)
a
b

1.1499999999999995

In [ ]:
np.dot(x, )

In [18]:
m = x.shape[0]
n = x.shape[1]
print("Rows: ", m, "Columns: ", n)

Rows:  2 Columns:  3


In [19]:
dj_dw = np.zeros(n)
dj_db = 0
    
dj_dw

array([0., 0., 0.])

In [20]:
dj_dw_sum = np.zeros(n)
dj_db_sum = 0

dj_dw_sum

array([0., 0., 0.])

In [23]:
w = np.array([0.1,0.1,0.1])
b = 0.1
for j in range(n):
    for i in range(m):
        func = np.dot(w, x[i]) + b
        dj_dw_i_j = (func - y[i])*x[i][j]
        dj_dw_sum[j] = dj_dw_sum[j] + dj_dw_i_j
    dj_dw[j] = dj_dw_sum[j]/m
    

In [24]:
for i in range(m):
    func = np.dot(w, x[i]) + b
    dj_db = func - y[i]
    dj_db_sum = dj_db_sum + dj_db
dj_db = dj_db/m
    

In [25]:
dj_dw

array([-0.95, -1.3 , -1.65])

In [26]:
dj_db

-0.19999999999999996